### ISSUE TITLE
command line variable not being considered

### ISSUE THREAD

**Issue by JamieMcDonnell** [sanusart/grunt-dev-prod-switch#4]
Hi there,

I detailed the issue I am having in full on stackOverflow:
http://stackoverflow.com/questions/41673366/command-line-variable-not-picked-up-by-dev-prod-switch

Would you mind taking a look and helping me to resolve where I am going wrong please?

Many thanks

Jamie

**Comment by sanusart** [comment]
Hey Jamie,

Sorry you having issues with this. We are on vacation traveling till 22nd.

I'll see what's going on after we get back to normal.

Regards,
Sasha

On Jan 16, 2017 12:54 PM, "JamieMcDonnell" <notifications@github.com> wrote:

Hi there,

I detailed the issue I am having in full on stackOverflow:
http://stackoverflow.com/questions/41673366/command-
line-variable-not-picked-up-by-dev-prod-switch

Would you mind taking a look and helping me to resolve where I am going
wrong please?

Many thanks

Jamie

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sanusart/grunt-dev-prod-switch/issues/4>, or mute the
thread

**Comment by JamieMcDonnell** [comment]
No problem at all, I got help resolving it - something I aparently
overlooked in your manual.

Thanks for the reply and enjoy your holiday ;)

Regards

Jamie

**Comment by sanusart** [comment]
Oh great!

Thanks.

Regards,
Sasha

**Comment by sanusart** [comment]
Can be closed I guess.
